apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-dev
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgres-dev
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-dev
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=     # printf postgres | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # printf password | base64
---
apiVersion:  apps/v1
kind: StatefulSet
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
    role: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
      role: service
  serviceName: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
        role: service
    spec:
      containers:
        - name: postgres
          image: postgres:14.10
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-dev
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-dev
          ports:
            - containerPort: 5432
              name: postgres-dev
              protocol: TCP
          volumeMounts:
            - name: postgres-dev
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-dev
          persistentVolumeClaim:
            claimName: postgres-dev
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
    role: service
spec:
  selector:
    app: postgres-dev
    role: service
  type: NodePort
  ports:
    - name: postgres-dev
      port: 5432
      targetPort: 5432
      nodePort: 32100
      protocol: TCP